title: Reading Notes
description: hchen's learning notes
theme: just-the-docs

url: "https://hchenxa.github.io"
baseurl: "/reading-notes"

color_scheme: light

search_enabled: true
search.heading_level: 3

nav_sort: case_insensitive

back_to_top: true
back_to_top_text: "Back to top"

heading_anchors: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - "*.go"
  - "*.py"
  - "*.js"
  - "*.sum"
  - "*.mod"
  - "*.sh"
  - "*.html"
  - "*.css"
  - "*.cfg"
  - go/gin/templates/
  - go/rpc/
  - go/socket/
  - go/tips/
  - python/sample/
  - python/hello_world.py
  - javascript/example/
  - javascript/project/
  - kind/
  - node_modules/
  - Gemfile
  - Gemfile.lock
