title: Reading Notes
description: hchen's learning notes
theme: just-the-docs

url: "https://hchenxa.github.io"
baseurl: "/reading-notes"

color_scheme: light

search_enabled: true
search:
  heading_level: 3
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/

nav_sort: case_insensitive

back_to_top: true
back_to_top_text: "Back to top"

heading_anchors: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - go/gin/templates/
  - go/rpc/
  - go/socket/
  - go/tips/
  - python/sample/
  - python/hello_world.py
  - javascript/example/
  - javascript/project/
  - kind/
  - node_modules/
  - .venv/
  - appium/sample/
  - Gemfile
  - Gemfile.lock
