[Service]
Environment="HTTP_PROXY=http://__HOST_IP__:7890"
Environment="HTTPS_PROXY=http://__HOST_IP__:7890"
Environment="NO_PROXY=localhost,127.0.0.1,::1,10.89.0.0/24,10.0.0.0/8,10.244.0.0/16,10.96.0.0/16,192.168.0.0/16,.svc,.svc.cluster.local,*.svc"
